CREATE TABLE IF NOT EXISTS emails (
  id BIGSERIAL PRIMARY KEY,
  email TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS phone_numbers (
  id BIGSERIAL PRIMARY KEY,
  phone TEXT NOT NULL UNIQUE
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'repl') THEN
    CREATE ROLE repl WITH LOGIN REPLICATION PASSWORD '1234';
  END IF;
END
$$;
